---
eos1:
  hostname: 192.168.150.133
  groups:
    - veos

eos2:
  hostname: 192.168.150.133
  groups:
    - veos

eos3:
  hostname: 192.168.150.134
  groups:
    - veos

eos4:
  hostname: 192.168.150.137
  groups:
    - veos

cx-1:
  hostname: 192.168.150.135
  groups:
    - cx
